// Generado desde RAW_FOODS de src/App.jsx con "npm run manual-jarvis". No editar a mano.
export const GRUPOS_APP: string[] = ["Cereales","Menestras","Tubérculos","Carnes y aves","Pescados","Huevos","Lácteos","Frutas","Verduras","Grasas","Otros","Platos preparados","Postres","Galletas y snacks","Bebidas","Pescados y mariscos"];
export const ALIMENTOS_APP: string[] = [
  "Arroz blanco (crudo)",
  "Arroz blanco (cocido)",
  "Quinua (cruda)",
  "Quinua (cocida)",
  "Avena en hojuelas (cruda)",
  "Avena (cocida)",
  "Kiwicha (cruda)",
  "Kiwicha (cocida)",
  "Cañihua (cruda)",
  "Cañihua (cocida)",
  "Choclo (maíz) (crudo)",
  "Choclo (maíz) (cocido)",
  "Cereal cornflakes sin gluten",
  "Lenteja (cruda)",
  "Lenteja (cocida)",
  "Frejol canario (crudo)",
  "Frejol canario (cocido)",
  "Garbanzo (crudo)",
  "Garbanzo (cocido)",
  "Pallar (crudo)",
  "Pallar (cocido)",
  "Haba seca (cruda)",
  "Haba (cocida)",
  "Papa (cruda)",
  "Papa (cocida)",
  "Camote (crudo)",
  "Camote (cocido)",
  "Yuca (cruda)",
  "Yuca (cocida)",
  "Olluco (crudo)",
  "Olluco (cocido)",
  "Plátano bellaco (sancochado)",
  "Pollo pechuga (cruda)",
  "Pollo pechuga (cocida)",
  "Carne de res (bistec) (cruda)",
  "Carne de res (bistec) (cocida)",
  "Churrasco (cruda (sin hueso))",
  "Churrasco (cocida (sin hueso))",
  "Churrasco (cruda (con hueso))",
  "Churrasco (cocida (con hueso))",
  "Cerdo (lomo) (crudo)",
  "Cerdo (lomo) (cocido)",
  "Chuleta de cerdo (cocida)",
  "Mollejitas de pollo (cocidas)",
  "Bonito (crudo)",
  "Bonito (cocido)",
  "Atún (crudo)",
  "Atún (cocido)",
  "Huevo de gallina (crudo)",
  "Huevo de gallina (cocido)",
  "Huevo de gallina (frito)",
  "Huevo de codorniz (crudo)",
  "Huevo de codorniz (cocido)",
  "Leche entera",
  "Leche descremada",
  "Leche sin lactosa",
  "Yogur natural",
  "Queso fresco",
  "Plátano de seda (cruda)",
  "Manzana (cruda)",
  "Palta (cruda)",
  "Papaya (cruda)",
  "Mango (crudo)",
  "Mandarina (cruda)",
  "Ensalada de frutas (estimado - varía según receta)",
  "Naranja (cruda)",
  "Durazno (crudo)",
  "Piña (cruda)",
  "Uva (cruda)",
  "Fresa (cruda)",
  "Tomate (crudo)",
  "Lechuga (cruda)",
  "Zanahoria (cruda)",
  "Zanahoria (cocida)",
  "Brócoli (crudo)",
  "Brócoli (cocido)",
  "Espinaca (cruda)",
  "Espinaca (cocida)",
  "Zapallo (crudo)",
  "Zapallo (cocido)",
  "Vainita (cruda)",
  "Vainita (cocida)",
  "Aceite vegetal",
  "Mantequilla",
  "Maní (crudo)",
  "Pan francés",
  "Rapiditas Clásicas (Bimbo)",
  "Rapiditas Integrales (Bimbo)",
  "Rapiditas XL (Bimbo)",
  "Pan integral",
  "Pan árabe",
  "Pan árabe integral",
  "Jamonada",
  "Salchicha (hot dog)",
  "Tostadas",
  "Pan con jamonada",
  "Pan con pollo",
  "Pan con chicharrón",
  "Butifarra",
  "Hot dog",
  "Hamburguesa de carretilla",
  "Pizza americana",
  "Pollo broaster",
  "Salchipollo",
  "Sopa wantán",
  "Humita",
  "Picarones con miel",
  "Cancha serrana (tostada)",
  "Granola",
  "Mantequilla de maní",
  "Refresco de cebada (con azúcar)",
  "Cerveza",
  "Cachanga (frita)",
  "Chía (cruda)",
  "Pollo pierna (con piel) (cocida)",
  "Pollo pierna (sin piel) (cruda)",
  "Pollo encuentro (con piel) (cocido)",
  "Pollo encuentro (sin piel) (cocido)",
  "Pollo entrepierna (cocida)",
  "Pollo ala (con piel) (cocida)",
  "Pollo pechuga (con piel) (cocida)",
  "Pollo molido (cocido)",
  "Pollo menudencia (hígado) (cocido)",
  "Gallina (cocida)",
  "Carne de res (lomo fino) (cocida)",
  "Carne molida de res (cocida)",
  "Hígado de res (cocido)",
  "Arveja verde (cocida)",
  "Arveja partida (seca) (cocida)",
  "Frejol negro (cocido)",
  "Frejol panamito (cocido)",
  "Frejol castilla (cocido)",
  "Frejol bayo (cocido)",
  "Lenteja bebé (cocida)",
  "Tarwi (chocho) (cocido)",
  "Soya (cocida)",
  "Zapallo macre (cocido)",
  "Caigua (cruda)",
  "Zapallito italiano (cocido)",
  "Coliflor (cocida)",
  "Col / repollo (cruda)",
  "Betarraga (cocida)",
  "Poro (crudo)",
  "Nabo (cocido)",
  "Alcachofa (cocida)",
  "Champiñón (cocido)",
  "Choclo desgranado (cocido)",
  "Locro de zapallo",
  "Arroz con pato",
  "Carapulcra",
  "Olluquito con charqui",
  "Adobo de cerdo",
  "Ají de pollo",
  "Pollo al sillao",
  "Papa dorada al sillao (estimado - varía según receta)",
  "Frejolada (frejol con arroz)",
  "Menestra de lentejas con arroz",
  "Chanfainita",
  "Papa rellena",
  "Empanada de carne (horneada)",
  "Empanada de pollo (horneada)",
  "Empanada mixta (carne y pollo) (horneada)",
  "Tamal",
  "Juane",
  "Galleta Morocha (bañada en chocolate)",
  "Galleta de soda (salada)",
  "Galleta de vainilla (dulce, tipo Casino/Margarita)",
  "Galleta Casino (vainilla rellena)",
  "Galleta Margarita (vainilla rellena)",
  "Galleta Chomp (chispas de chocolate)",
  "Galleta Cua Cua (wafer con chocolate)",
  "Galleta Club Social (cracker)",
  "Pachamanca",
  "Sopa de pollo con fideos",
  "Chupe de camarones",
  "Parihuela",
  "Café negro (con azúcar)",
  "Café con leche (con azúcar)",
  "Té / infusión (con azúcar)",
  "Jugo de papaya (con azúcar)",
  "Jugo de piña (con azúcar)",
  "Jugo de naranja (con azúcar)",
  "Jugo de maracuyá (con azúcar)",
  "Jugo surtido (con azúcar)",
  "Limonada (sin azúcar)",
  "Emoliente (con azúcar)",
  "Avena / quinua de bebida (con azúcar)",
  "Chicha morada (sin azúcar)",
  "Atún en lata en agua (escurrido)",
  "Atún en lata en aceite (escurrido)",
  "Atún en lata en aceite (sin escurrir)",
  "Clara de huevo (cocida)",
  "Yema de huevo (cocida)",
  "Ají de gallina",
  "Arroz con pollo",
  "Pollo a la brasa (solo la presa)",
  "Pollo a la brasa con papas y ensalada",
  "Pollada (pollo frito)",
  "Ceviche de pescado",
  "Lomo saltado",
  "Arroz chaufa",
  "Tallarines rojos con pollo",
  "Tallarines rojos con carne molida",
  "Tallarines verdes",
  "Causa limeña",
  "Papa a la huancaína",
  "Ocopa arequipeña",
  "Seco de res con frejoles",
  "Cau cau",
  "Tacu tacu",
  "Rocoto relleno",
  "Anticucho de corazón",
  "Chicharrón de pollo",
  "Chicharrón de chancho",
  "Arroz con mariscos",
  "Hamburguesa clásica (Bembos)",
  "Alitas broaster (Bembos)",
  "Alitas crocantes (carrito) (estimado - varía según receta)",
  "Alitas BBQ (carrito) (estimado - varía según receta)",
  "Alitas acevichadas (carrito) (estimado - varía según receta)",
  "Alitas búfalo (carrito) (estimado - varía según receta)",
  "Papas fritas (comida rápida)",
  "Hamburguesa clásica (McDonald's)",
  "McNuggets",
  "Pieza de pollo Original (KFC)",
  "Pieza de pollo Crujiente (KFC)",
  "Alitas picantes (KFC)",
  "Twister (KFC)",
  "Milanesa de pollo",
  "Torreja de espinaca y tomate",
  "Filete de pollo frito (estimado - varía según receta)",
  "Pescado frito",
  "Sudado de pescado",
  "Escabeche de pollo",
  "Salchipapa",
  "Pollo al horno",
  "Pollo a la olla (presa con papa y verduras)",
  "Pollo a la olla con arroz",
  "Estofado de pollo",
  "Estofado de carne",
  "Aguadito de pollo",
  "Caldo de gallina",
  "Sopa a la minuta",
  "Menestrón",
  "Ensalada de pollo",
  "Sándwich de pollo",
  "Panqueques de avena (estimado - varía según receta)",
  "Wafle de avena (estimado - varía según receta)",
  "Fideos / pasta (crudos)",
  "Fideos / pasta (cocidos)",
  "Fideos integrales (cocidos)",
  "Tallarín saltado (plato)",
  "Jugo de papaya natural",
  "Jugo de piña natural",
  "Jugo de maracuyá natural",
  "Jugo de fresa natural",
  "Jugo surtido (papaya+piña+naranja)",
  "Limonada con azúcar",
  "Picarón",
  "Mazamorra morada",
  "Arroz con leche",
  "Combinado (mazamorra + arroz con leche)",
  "Suspiro a la limeña",
  "Turrón de Doña Pepa",
  "Alfajor",
  "Torta de chocolate",
  "Helado de vainilla",
  "Gelatina preparada",
  "Flan / crema volteada",
  "Churro relleno",
  "Queque simple",
  "Keke de plátano",
  "Keke de naranja",
  "Keke de vainilla",
  "Keke de zanahoria",
  "Keke marmoleado",
  "Keke de arándanos",
  "Panetón",
  "Torta tres leches",
  "Cocada",
  "Manjar blanco",
  "Leche asada",
  "Chocolate con leche",
  "Galleta dulce rellena",
  "Café negro sin azúcar",
  "Café con leche",
  "Café con leche descremada",
  "Capuchino",
  "Capuchino (con azúcar)",
  "Té / infusión sin azúcar",
  "Agua",
  "Jugo de naranja natural",
  "Gaseosa regular",
  "Gaseosa dietética",
  "Chicha morada con azúcar",
  "Emoliente sin azúcar",
  "Leche de almendras sin azúcar",
  "Leche de coco",
  "Yogur bebible",
  "Azúcar blanca",
  "Miel de abeja",
  "Mermelada",
  "Galleta de soda",
  "Avena instantánea en polvo",
  "Proteína en polvo (whey)",
  "Crema de arroz (estimado - varía según marca)",
  "Proteína en polvo (isolate)",
  "Aceite de oliva",
  "Almendras (crudas)",
  "Nueces (crudas)",
  "Pecanas (crudas)",
  "Arándanos (crudos)",
  "Sandía (cruda)",
  "Melón (crudo)",
  "Pera (cruda)",
  "Tuna (cruda (pelada))",
  "Pepino (crudo)",
  "Pimiento (crudo)",
  "Cebolla (cruda)",
  "Apio (crudo)",
  "Pollo pierna (sin piel) (cocida)",
  "Pavo pechuga (cocida)",
  "Jamón de pavo",
  "Jamón inglés",
  "Chorizo parrillero",
  "Trucha (cocida)",
  "Langostinos (cocidos)",
  "Queso parmesano",
  "Yogur griego natural",
  "Yogur saborizado (con azúcar)",
  "Sandwich de pollo (PECAFIT)",
  "Sandwich de atún (PECAFIT)",
  "Omelette (PECAFIT)",
  "Bowl de avena (PECAFIT)",
  "Waffles de avena y plátano (PECAFIT)",
  "Waffle de beterraga y mango (PECAFIT)",
  "Filete de pollo (PECAFIT)",
  "Quinua chaufa (PECAFIT)",
  "Bowl andino (PECAFIT)",
  "Bowl Super Power (PECAFIT)",
  "Trucha (PECAFIT)",
  "Peca Power Meat (PECAFIT)",
  "Wrap proteico (PECAFIT)",
  "Wrap filete de pollo (PECAFIT)",
  "Wrap crocante (PECAFIT)",
  "Cake de plátano (PECAFIT)",
  "Torta de cacao (PECAFIT)",
  "Cheesecake (PECAFIT)",
  "Parfait (PECAFIT)",
];
