// Generado desde RAW_FOODS de src/App.jsx con "npm run manual-jarvis". No editar a mano.
// Nombre como sale en la app y calorías por 100 g (lo usa api/cron/verificar-alimentos.js).
export const ALIMENTOS_APP = [
  {"etiqueta":"Arroz blanco (crudo)","kcal":365},
  {"etiqueta":"Arroz blanco (cocido)","kcal":130},
  {"etiqueta":"Arroz verde (cocido)","kcal":160},
  {"etiqueta":"Arroz amarillo (a la jardinera) (cocido)","kcal":150},
  {"etiqueta":"Arroz aderezado (con ají panca) (cocido)","kcal":165},
  {"etiqueta":"Arroz chaufa (solo el arroz) (cocido)","kcal":156},
  {"etiqueta":"Quinua (cruda)","kcal":368},
  {"etiqueta":"Quinua (cocida)","kcal":120},
  {"etiqueta":"Avena en hojuelas (cruda)","kcal":389},
  {"etiqueta":"Avena (cocida)","kcal":71},
  {"etiqueta":"Kiwicha (cruda)","kcal":371},
  {"etiqueta":"Kiwicha (cocida)","kcal":102},
  {"etiqueta":"Cañihua (cruda)","kcal":350},
  {"etiqueta":"Cañihua (cocida)","kcal":114},
  {"etiqueta":"Choclo (maíz) (crudo)","kcal":96},
  {"etiqueta":"Choclo (maíz) (cocido)","kcal":90},
  {"etiqueta":"Cereal cornflakes sin gluten","kcal":378},
  {"etiqueta":"Lenteja (cruda)","kcal":353},
  {"etiqueta":"Lenteja (cocida)","kcal":116},
  {"etiqueta":"Frejol canario (crudo)","kcal":341},
  {"etiqueta":"Frejol canario (cocido)","kcal":127},
  {"etiqueta":"Garbanzo (crudo)","kcal":364},
  {"etiqueta":"Garbanzo (cocido)","kcal":164},
  {"etiqueta":"Pallar (crudo)","kcal":338},
  {"etiqueta":"Pallar (cocido)","kcal":113},
  {"etiqueta":"Haba seca (cruda)","kcal":341},
  {"etiqueta":"Haba (cocida)","kcal":110},
  {"etiqueta":"Papa (cruda)","kcal":77},
  {"etiqueta":"Papa (cocida)","kcal":87},
  {"etiqueta":"Camote (crudo)","kcal":86},
  {"etiqueta":"Camote (cocido)","kcal":90},
  {"etiqueta":"Yuca (cruda)","kcal":160},
  {"etiqueta":"Yuca (cocida)","kcal":112},
  {"etiqueta":"Olluco (crudo)","kcal":62},
  {"etiqueta":"Olluco (cocido)","kcal":54},
  {"etiqueta":"Plátano bellaco (sancochado)","kcal":116},
  {"etiqueta":"Pollo pechuga (cruda)","kcal":110},
  {"etiqueta":"Pollo pechuga (cocida)","kcal":165},
  {"etiqueta":"Carne de res (bistec) (cruda)","kcal":143},
  {"etiqueta":"Carne de res (bistec) (cocida)","kcal":217},
  {"etiqueta":"Churrasco (cruda (sin hueso))","kcal":155},
  {"etiqueta":"Churrasco (cocida (sin hueso))","kcal":235},
  {"etiqueta":"Churrasco (cruda (con hueso))","kcal":140},
  {"etiqueta":"Churrasco (cocida (con hueso))","kcal":212},
  {"etiqueta":"Cerdo (lomo) (crudo)","kcal":143},
  {"etiqueta":"Cerdo (lomo) (cocido)","kcal":212},
  {"etiqueta":"Chuleta de cerdo (cocida)","kcal":231},
  {"etiqueta":"Mollejitas de pollo (cocidas)","kcal":154},
  {"etiqueta":"Bonito (crudo)","kcal":110},
  {"etiqueta":"Bonito (cocido)","kcal":136},
  {"etiqueta":"Atún (crudo)","kcal":116},
  {"etiqueta":"Atún (cocido)","kcal":132},
  {"etiqueta":"Huevo de gallina (crudo)","kcal":143},
  {"etiqueta":"Huevo de gallina (cocido)","kcal":155},
  {"etiqueta":"Huevo de gallina (frito)","kcal":196},
  {"etiqueta":"Huevo de codorniz (crudo)","kcal":158},
  {"etiqueta":"Huevo de codorniz (cocido)","kcal":158},
  {"etiqueta":"Leche entera","kcal":61},
  {"etiqueta":"Leche descremada","kcal":34},
  {"etiqueta":"Leche sin lactosa","kcal":46},
  {"etiqueta":"Yogur natural","kcal":61},
  {"etiqueta":"Queso fresco","kcal":264},
  {"etiqueta":"Plátano de seda (cruda)","kcal":89},
  {"etiqueta":"Manzana (cruda)","kcal":52},
  {"etiqueta":"Palta (cruda)","kcal":160},
  {"etiqueta":"Papaya (cruda)","kcal":43},
  {"etiqueta":"Mango (crudo)","kcal":60},
  {"etiqueta":"Mandarina (cruda)","kcal":53},
  {"etiqueta":"Ensalada de frutas (estimado - varía según receta)","kcal":55},
  {"etiqueta":"Naranja (cruda)","kcal":47},
  {"etiqueta":"Durazno (crudo)","kcal":39},
  {"etiqueta":"Piña (cruda)","kcal":50},
  {"etiqueta":"Uva (cruda)","kcal":69},
  {"etiqueta":"Fresa (cruda)","kcal":32},
  {"etiqueta":"Tomate (crudo)","kcal":18},
  {"etiqueta":"Lechuga (cruda)","kcal":15},
  {"etiqueta":"Zanahoria (cruda)","kcal":41},
  {"etiqueta":"Zanahoria (cocida)","kcal":35},
  {"etiqueta":"Brócoli (crudo)","kcal":34},
  {"etiqueta":"Brócoli (cocido)","kcal":35},
  {"etiqueta":"Espinaca (cruda)","kcal":23},
  {"etiqueta":"Espinaca (cocida)","kcal":23},
  {"etiqueta":"Zapallo (crudo)","kcal":26},
  {"etiqueta":"Zapallo (cocido)","kcal":20},
  {"etiqueta":"Vainita (cruda)","kcal":31},
  {"etiqueta":"Vainita (cocida)","kcal":35},
  {"etiqueta":"Aceite vegetal","kcal":884},
  {"etiqueta":"Mantequilla","kcal":717},
  {"etiqueta":"Maní (crudo)","kcal":567},
  {"etiqueta":"Pan francés","kcal":274},
  {"etiqueta":"Rapiditas Clásicas (Bimbo)","kcal":315},
  {"etiqueta":"Rapiditas Integrales (Bimbo)","kcal":292},
  {"etiqueta":"Rapiditas XL (Bimbo)","kcal":315},
  {"etiqueta":"Pan integral","kcal":247},
  {"etiqueta":"Pan árabe","kcal":275},
  {"etiqueta":"Pan árabe integral","kcal":262},
  {"etiqueta":"Jamonada","kcal":250},
  {"etiqueta":"Salchicha (hot dog)","kcal":290},
  {"etiqueta":"Tostadas","kcal":390},
  {"etiqueta":"Pan con jamonada","kcal":265},
  {"etiqueta":"Pan con pollo","kcal":230},
  {"etiqueta":"Pan con chicharrón","kcal":280},
  {"etiqueta":"Butifarra","kcal":230},
  {"etiqueta":"Hot dog","kcal":260},
  {"etiqueta":"Hamburguesa de carretilla","kcal":250},
  {"etiqueta":"Pizza americana","kcal":266},
  {"etiqueta":"Pollo broaster","kcal":290},
  {"etiqueta":"Salchipollo","kcal":260},
  {"etiqueta":"Sopa wantán","kcal":60},
  {"etiqueta":"Humita","kcal":230},
  {"etiqueta":"Picarones con miel","kcal":330},
  {"etiqueta":"Cancha serrana (tostada)","kcal":470},
  {"etiqueta":"Granola","kcal":471},
  {"etiqueta":"Mantequilla de maní","kcal":588},
  {"etiqueta":"Refresco de cebada (con azúcar)","kcal":40},
  {"etiqueta":"Cerveza","kcal":43},
  {"etiqueta":"Cachanga (frita)","kcal":320},
  {"etiqueta":"Chía (cruda)","kcal":486},
  {"etiqueta":"Pollo pierna (con piel) (cocida)","kcal":232},
  {"etiqueta":"Pato (sin piel) (cocido)","kcal":201},
  {"etiqueta":"Cerdo (costilla) (cocida)","kcal":355},
  {"etiqueta":"Pollo pierna (sin piel) (cruda)","kcal":120},
  {"etiqueta":"Pollo encuentro (con piel) (cocido)","kcal":245},
  {"etiqueta":"Pollo encuentro (sin piel) (cocido)","kcal":178},
  {"etiqueta":"Pollo entrepierna (cocida)","kcal":219},
  {"etiqueta":"Pollo ala (con piel) (cocida)","kcal":266},
  {"etiqueta":"Pollo pechuga (con piel) (cocida)","kcal":197},
  {"etiqueta":"Pollo molido (cocido)","kcal":189},
  {"etiqueta":"Pollo menudencia (hígado) (cocido)","kcal":167},
  {"etiqueta":"Gallina (cocida)","kcal":237},
  {"etiqueta":"Carne de res (lomo fino) (cocida)","kcal":180},
  {"etiqueta":"Carne molida de res (cocida)","kcal":250},
  {"etiqueta":"Hígado de res (cocido)","kcal":175},
  {"etiqueta":"Arveja verde (cocida)","kcal":84},
  {"etiqueta":"Arveja partida (seca) (cocida)","kcal":118},
  {"etiqueta":"Frejol negro (cocido)","kcal":132},
  {"etiqueta":"Frejol panamito (cocido)","kcal":127},
  {"etiqueta":"Frejol castilla (cocido)","kcal":116},
  {"etiqueta":"Frejol bayo (cocido)","kcal":127},
  {"etiqueta":"Lenteja bebé (cocida)","kcal":116},
  {"etiqueta":"Tarwi (chocho) (cocido)","kcal":151},
  {"etiqueta":"Soya (cocida)","kcal":173},
  {"etiqueta":"Zapallo macre (cocido)","kcal":34},
  {"etiqueta":"Caigua (cruda)","kcal":20},
  {"etiqueta":"Zapallito italiano (cocido)","kcal":17},
  {"etiqueta":"Coliflor (cocida)","kcal":23},
  {"etiqueta":"Col / repollo (cruda)","kcal":25},
  {"etiqueta":"Betarraga (cocida)","kcal":44},
  {"etiqueta":"Poro (crudo)","kcal":61},
  {"etiqueta":"Nabo (cocido)","kcal":22},
  {"etiqueta":"Alcachofa (cocida)","kcal":53},
  {"etiqueta":"Champiñón (cocido)","kcal":28},
  {"etiqueta":"Choclo desgranado (cocido)","kcal":96},
  {"etiqueta":"Locro de zapallo","kcal":95},
  {"etiqueta":"Arroz con pato","kcal":178},
  {"etiqueta":"Carapulcra","kcal":165},
  {"etiqueta":"Olluquito con charqui","kcal":110},
  {"etiqueta":"Adobo de cerdo","kcal":175},
  {"etiqueta":"Ají de pollo","kcal":160},
  {"etiqueta":"Pollo al sillao","kcal":185},
  {"etiqueta":"Papa dorada al sillao (estimado - varía según receta)","kcal":140},
  {"etiqueta":"Frejolada (frejol con arroz)","kcal":140},
  {"etiqueta":"Menestra de lentejas con arroz","kcal":130},
  {"etiqueta":"Chanfainita","kcal":145},
  {"etiqueta":"Papa rellena","kcal":210},
  {"etiqueta":"Empanada de carne (horneada)","kcal":255},
  {"etiqueta":"Empanada de pollo (horneada)","kcal":230},
  {"etiqueta":"Empanada mixta (carne y pollo) (horneada)","kcal":245},
  {"etiqueta":"Tamal","kcal":235},
  {"etiqueta":"Juane","kcal":190},
  {"etiqueta":"Galleta Morocha (bañada en chocolate)","kcal":488},
  {"etiqueta":"Galleta de soda (salada)","kcal":433},
  {"etiqueta":"Galleta de vainilla (dulce, tipo Casino/Margarita)","kcal":434},
  {"etiqueta":"Galleta Casino (vainilla rellena)","kcal":478},
  {"etiqueta":"Galleta Margarita (vainilla rellena)","kcal":480},
  {"etiqueta":"Galleta Chomp (chispas de chocolate)","kcal":485},
  {"etiqueta":"Galleta Cua Cua (wafer con chocolate)","kcal":515},
  {"etiqueta":"Galleta Club Social (cracker)","kcal":480},
  {"etiqueta":"Pachamanca","kcal":195},
  {"etiqueta":"Sopa de pollo con fideos","kcal":75},
  {"etiqueta":"Chupe de camarones","kcal":105},
  {"etiqueta":"Parihuela","kcal":75},
  {"etiqueta":"Café negro (con azúcar)","kcal":15},
  {"etiqueta":"Café con leche (con azúcar)","kcal":58},
  {"etiqueta":"Té / infusión (con azúcar)","kcal":14},
  {"etiqueta":"Jugo de papaya (con azúcar)","kcal":58},
  {"etiqueta":"Jugo de piña (con azúcar)","kcal":66},
  {"etiqueta":"Jugo de naranja (con azúcar)","kcal":63},
  {"etiqueta":"Jugo de maracuyá (con azúcar)","kcal":70},
  {"etiqueta":"Jugo surtido (con azúcar)","kcal":63},
  {"etiqueta":"Limonada (sin azúcar)","kcal":8},
  {"etiqueta":"Emoliente (con azúcar)","kcal":26},
  {"etiqueta":"Avena / quinua de bebida (con azúcar)","kcal":68},
  {"etiqueta":"Chicha morada (sin azúcar)","kcal":18},
  {"etiqueta":"Atún en lata en agua (escurrido)","kcal":116},
  {"etiqueta":"Atún en lata en aceite (escurrido)","kcal":198},
  {"etiqueta":"Atún en lata en aceite (sin escurrir)","kcal":250},
  {"etiqueta":"Clara de huevo (cocida)","kcal":52},
  {"etiqueta":"Yema de huevo (cocida)","kcal":322},
  {"etiqueta":"Ají de gallina","kcal":165},
  {"etiqueta":"Arroz con pollo","kcal":150},
  {"etiqueta":"Pollo a la brasa (solo la presa)","kcal":215},
  {"etiqueta":"Pollo a la brasa con papas y ensalada","kcal":232},
  {"etiqueta":"Pollada (pollo frito)","kcal":250},
  {"etiqueta":"Ceviche de pescado","kcal":85},
  {"etiqueta":"Lomo saltado","kcal":175},
  {"etiqueta":"Arroz chaufa","kcal":165},
  {"etiqueta":"Arroz chaufa de carne","kcal":167},
  {"etiqueta":"Arroz chaufa de chancho","kcal":166},
  {"etiqueta":"Arroz chaufa especial","kcal":169},
  {"etiqueta":"Arroz a la jardinera","kcal":175},
  {"etiqueta":"Arroz con chancho","kcal":202},
  {"etiqueta":"Ensalada rusa","kcal":105},
  {"etiqueta":"Tallarines rojos con pollo","kcal":170},
  {"etiqueta":"Tallarines rojos con carne molida","kcal":160},
  {"etiqueta":"Tallarines verdes","kcal":185},
  {"etiqueta":"Causa limeña","kcal":145},
  {"etiqueta":"Papa a la huancaína","kcal":150},
  {"etiqueta":"Ocopa arequipeña","kcal":160},
  {"etiqueta":"Seco de res con frejoles","kcal":160},
  {"etiqueta":"Cau cau","kcal":120},
  {"etiqueta":"Tacu tacu","kcal":200},
  {"etiqueta":"Rocoto relleno","kcal":180},
  {"etiqueta":"Anticucho de corazón","kcal":150},
  {"etiqueta":"Chicharrón de pollo","kcal":260},
  {"etiqueta":"Chicharrón de chancho","kcal":350},
  {"etiqueta":"Arroz con mariscos","kcal":155},
  {"etiqueta":"Hamburguesa clásica (Bembos)","kcal":248},
  {"etiqueta":"Alitas broaster (Bembos)","kcal":290},
  {"etiqueta":"Alitas crocantes (carrito) (estimado - varía según receta)","kcal":270},
  {"etiqueta":"Alitas BBQ (carrito) (estimado - varía según receta)","kcal":250},
  {"etiqueta":"Alitas acevichadas (carrito) (estimado - varía según receta)","kcal":260},
  {"etiqueta":"Alitas búfalo (carrito) (estimado - varía según receta)","kcal":280},
  {"etiqueta":"Papas fritas (comida rápida)","kcal":312},
  {"etiqueta":"Hamburguesa clásica (McDonald's)","kcal":264},
  {"etiqueta":"McNuggets","kcal":296},
  {"etiqueta":"Pieza de pollo Original (KFC)","kcal":241},
  {"etiqueta":"Pieza de pollo Crujiente (KFC)","kcal":270},
  {"etiqueta":"Alitas picantes (KFC)","kcal":319},
  {"etiqueta":"Twister (KFC)","kcal":242},
  {"etiqueta":"Milanesa de pollo","kcal":250},
  {"etiqueta":"Torreja de espinaca y tomate","kcal":175},
  {"etiqueta":"Filete de pollo frito (estimado - varía según receta)","kcal":230},
  {"etiqueta":"Pescado frito","kcal":200},
  {"etiqueta":"Sudado de pescado","kcal":95},
  {"etiqueta":"Escabeche de pollo","kcal":130},
  {"etiqueta":"Salchipapa","kcal":270},
  {"etiqueta":"Pollo al horno","kcal":190},
  {"etiqueta":"Pollo a la olla (presa con papa y verduras)","kcal":130},
  {"etiqueta":"Pollo a la olla con arroz","kcal":128},
  {"etiqueta":"Estofado de pollo","kcal":130},
  {"etiqueta":"Estofado de carne","kcal":150},
  {"etiqueta":"Aguadito de pollo","kcal":70},
  {"etiqueta":"Caldo de gallina","kcal":65},
  {"etiqueta":"Sopa a la minuta","kcal":80},
  {"etiqueta":"Menestrón","kcal":90},
  {"etiqueta":"Ensalada de pollo","kcal":110},
  {"etiqueta":"Sándwich de pollo","kcal":230},
  {"etiqueta":"Panqueques de avena (estimado - varía según receta)","kcal":180},
  {"etiqueta":"Wafle de avena (estimado - varía según receta)","kcal":200},
  {"etiqueta":"Fideos / pasta (crudos)","kcal":371},
  {"etiqueta":"Fideos / pasta (cocidos)","kcal":158},
  {"etiqueta":"Fideos integrales (cocidos)","kcal":124},
  {"etiqueta":"Tallarín saltado (plato)","kcal":168},
  {"etiqueta":"Jugo de papaya natural","kcal":40},
  {"etiqueta":"Jugo de piña natural","kcal":48},
  {"etiqueta":"Jugo de maracuyá natural","kcal":52},
  {"etiqueta":"Jugo de fresa natural","kcal":35},
  {"etiqueta":"Jugo surtido (papaya+piña+naranja)","kcal":45},
  {"etiqueta":"Limonada con azúcar","kcal":40},
  {"etiqueta":"Picarón","kcal":290},
  {"etiqueta":"Mazamorra morada","kcal":105},
  {"etiqueta":"Arroz con leche","kcal":130},
  {"etiqueta":"Combinado (mazamorra + arroz con leche)","kcal":118},
  {"etiqueta":"Suspiro a la limeña","kcal":330},
  {"etiqueta":"Turrón de Doña Pepa","kcal":395},
  {"etiqueta":"Alfajor","kcal":425},
  {"etiqueta":"Torta de chocolate","kcal":370},
  {"etiqueta":"Helado de vainilla","kcal":207},
  {"etiqueta":"Gelatina preparada","kcal":62},
  {"etiqueta":"Flan / crema volteada","kcal":190},
  {"etiqueta":"Churro relleno","kcal":380},
  {"etiqueta":"Queque simple","kcal":340},
  {"etiqueta":"Keke de plátano","kcal":277},
  {"etiqueta":"Keke de naranja","kcal":320},
  {"etiqueta":"Keke de vainilla","kcal":340},
  {"etiqueta":"Keke de zanahoria","kcal":370},
  {"etiqueta":"Keke marmoleado","kcal":350},
  {"etiqueta":"Keke de arándanos","kcal":330},
  {"etiqueta":"Panetón","kcal":340},
  {"etiqueta":"Torta tres leches","kcal":285},
  {"etiqueta":"Cocada","kcal":460},
  {"etiqueta":"Manjar blanco","kcal":315},
  {"etiqueta":"Leche asada","kcal":150},
  {"etiqueta":"Chocolate con leche","kcal":535},
  {"etiqueta":"Galleta dulce rellena","kcal":480},
  {"etiqueta":"Café negro sin azúcar","kcal":2},
  {"etiqueta":"Café con leche","kcal":42},
  {"etiqueta":"Café con leche descremada","kcal":22},
  {"etiqueta":"Capuchino","kcal":40},
  {"etiqueta":"Capuchino (con azúcar)","kcal":58},
  {"etiqueta":"Té / infusión sin azúcar","kcal":1},
  {"etiqueta":"Agua","kcal":0},
  {"etiqueta":"Jugo de naranja natural","kcal":45},
  {"etiqueta":"Gaseosa regular","kcal":42},
  {"etiqueta":"Gaseosa dietética","kcal":0},
  {"etiqueta":"Chicha morada con azúcar","kcal":55},
  {"etiqueta":"Emoliente sin azúcar","kcal":8},
  {"etiqueta":"Leche de almendras sin azúcar","kcal":15},
  {"etiqueta":"Leche de coco","kcal":180},
  {"etiqueta":"Yogur bebible","kcal":70},
  {"etiqueta":"Azúcar blanca","kcal":387},
  {"etiqueta":"Miel de abeja","kcal":304},
  {"etiqueta":"Mermelada","kcal":278},
  {"etiqueta":"Galleta de soda","kcal":421},
  {"etiqueta":"Avena instantánea en polvo","kcal":379},
  {"etiqueta":"Proteína en polvo (whey)","kcal":400},
  {"etiqueta":"Crema de arroz (estimado - varía según marca)","kcal":375},
  {"etiqueta":"Proteína en polvo (isolate)","kcal":380},
  {"etiqueta":"Aceite de oliva","kcal":884},
  {"etiqueta":"Mayonesa","kcal":680},
  {"etiqueta":"Almendras (crudas)","kcal":579},
  {"etiqueta":"Nueces (crudas)","kcal":654},
  {"etiqueta":"Pecanas (crudas)","kcal":691},
  {"etiqueta":"Arándanos (crudos)","kcal":57},
  {"etiqueta":"Sandía (cruda)","kcal":30},
  {"etiqueta":"Melón (crudo)","kcal":34},
  {"etiqueta":"Pera (cruda)","kcal":57},
  {"etiqueta":"Tuna (cruda (pelada))","kcal":41},
  {"etiqueta":"Pepino (crudo)","kcal":15},
  {"etiqueta":"Pimiento (crudo)","kcal":31},
  {"etiqueta":"Cebolla (cruda)","kcal":40},
  {"etiqueta":"Apio (crudo)","kcal":16},
  {"etiqueta":"Pollo pierna (sin piel) (cocida)","kcal":177},
  {"etiqueta":"Pavo pechuga (cocida)","kcal":135},
  {"etiqueta":"Pavita muslo (medallón, sin piel) (cocida)","kcal":170},
  {"etiqueta":"Jamón de pavo","kcal":104},
  {"etiqueta":"Jamón inglés","kcal":145},
  {"etiqueta":"Chorizo parrillero","kcal":330},
  {"etiqueta":"Trucha (cocida)","kcal":148},
  {"etiqueta":"Langostinos (cocidos)","kcal":99},
  {"etiqueta":"Queso parmesano","kcal":392},
  {"etiqueta":"Yogur griego natural","kcal":59},
  {"etiqueta":"Yogur saborizado (con azúcar)","kcal":90},
  {"etiqueta":"Chocolatada navideña","kcal":96},
  {"etiqueta":"Pavo al horno (con piel)","kcal":190},
  {"etiqueta":"Lechón al horno","kcal":280},
  {"etiqueta":"Puré de manzana","kcal":75},
  {"etiqueta":"Arroz árabe","kcal":175},
  {"etiqueta":"Ensalada de manzana navideña","kcal":152},
  {"etiqueta":"Ensalada de pollo navideña","kcal":162},
  {"etiqueta":"Puré de camote","kcal":121},
  {"etiqueta":"Pierna de cerdo al horno","kcal":233},
  {"etiqueta":"Panetón con chispas de chocolate","kcal":378},
  {"etiqueta":"Vino espumante (champán)","kcal":76},
  {"etiqueta":"Sandwich de pollo (PECAFIT)","kcal":367.36},
  {"etiqueta":"Sandwich de atún (PECAFIT)","kcal":345.52},
  {"etiqueta":"Omelette (PECAFIT)","kcal":180.36},
  {"etiqueta":"Bowl de avena (PECAFIT)","kcal":247.4},
  {"etiqueta":"Waffles de avena y plátano (PECAFIT)","kcal":446.43},
  {"etiqueta":"Waffle de beterraga y mango (PECAFIT)","kcal":403.13},
  {"etiqueta":"Filete de pollo (PECAFIT)","kcal":217.1},
  {"etiqueta":"Quinua chaufa (PECAFIT)","kcal":250.93},
  {"etiqueta":"Bowl andino (PECAFIT)","kcal":220.19},
  {"etiqueta":"Bowl Super Power (PECAFIT)","kcal":262.76},
  {"etiqueta":"Trucha (PECAFIT)","kcal":123.28},
  {"etiqueta":"Peca Power Meat (PECAFIT)","kcal":114.75},
  {"etiqueta":"Wrap proteico (PECAFIT)","kcal":190.96},
  {"etiqueta":"Wrap filete de pollo (PECAFIT)","kcal":146.38},
  {"etiqueta":"Wrap crocante (PECAFIT)","kcal":128.21},
  {"etiqueta":"Cake de plátano (PECAFIT)","kcal":566.74},
  {"etiqueta":"Torta de cacao (PECAFIT)","kcal":465.39},
  {"etiqueta":"Cheesecake (PECAFIT)","kcal":426.54},
  {"etiqueta":"Parfait (PECAFIT)","kcal":138.27},
];
