// Los platos que tienen su página en jonahbeast.com/calorias/<slug>.
// Las calorías y porciones NO van aquí: salen de la lista de alimentos de la
// app (RAW_FOODS y sus medidas en src/App.jsx), así la página y la app
// siempre dicen lo mismo. Aquí solo va lo que la app no tiene: el nombre
// para la página, el grupo y el consejo de Jonah (en su voz).
//
//   alimento: nombre exacto en RAW_FOODS (y estado, si hay varios con el
//             mismo nombre).
//   porcion:  (opcional) qué medida se muestra en grande; si no, la primera.
//   etiqueta: (opcional) cómo se llama esa medida en grande.
//   el:       (opcional) artículo si no es "el": 'la', 'los' o 'las'.
//   frase:    (opcional) cómo se dice la porción en una oración; si no,
//             "<etiqueta> de <plato>" (ej. "Un plato de lomo saltado").
//   aclara:   (opcional) aclaración bajo el número grande.

export const GRUPOS = [
  { id: 'segundos', titulo: 'Segundos y platos de fondo' },
  { id: 'arroces', titulo: 'Arroces y tallarines' },
  { id: 'mar', titulo: 'Pescados y mariscos' },
  { id: 'entradas', titulo: 'Entradas' },
  { id: 'sopas', titulo: 'Sopas y caldos' },
  { id: 'paso', titulo: 'Al paso' },
  { id: 'postres', titulo: 'Postres' },
  { id: 'bebidas', titulo: 'Bebidas' },
  { id: 'navidad', titulo: 'Navidad' },
];

export const PLATOS = [
  // Segundos y platos de fondo
  { slug: 'lomo-saltado', alimento: 'Lomo saltado', nombre: 'Lomo saltado', grupo: 'segundos',
    consejo: 'Yo me lo como igual, solo le bajo el arroz a la mitad y le pido más cebolla y tomate. No se trata de dejar tu lomo, sino de saber cuánto comes.' },
  { slug: 'aji-de-gallina', alimento: 'Ají de gallina', nombre: 'Ají de gallina', grupo: 'segundos',
    consejo: 'La crema lleva pan, leche y queso, por eso suma rápido. Sírvete una porción normal, acompáñala con la papa en vez de mucho arroz y disfrútala sin culpa.' },
  { slug: 'pollo-a-la-brasa', etiqueta: 'Un cuarto con papas', frase: 'Un cuarto de pollo a la brasa con papas', alimento: 'Pollo a la brasa con papas y ensalada', nombre: 'Pollo a la brasa con papas', grupo: 'segundos',
    consejo: 'Un cuarto con papas es casi una comida y media. Si quieres comerlo seguido, pide octavo, cambia parte de las papas por más ensalada y ojo con las cremas, que también suman.' },
  { slug: 'seco-de-res-con-frejoles', alimento: 'Seco de res con frejoles', nombre: 'Seco de res con frejoles', grupo: 'segundos',
    consejo: 'Buen plato: la carne y los frejoles te dan proteína y te llenan. Si le bajas un poco el arroz, queda un almuerzo muy completo.' },
  { slug: 'cau-cau', alimento: 'Cau cau', nombre: 'Cau cau', grupo: 'segundos',
    consejo: 'Es de los segundos más livianos. Lo que más suma es el arroz que lo acompaña: con media porción de arroz ya estás bien.' },
  { slug: 'tacu-tacu', alimento: 'Tacu tacu', nombre: 'Tacu tacu', grupo: 'segundos',
    consejo: 'Es arroz con frejol frito en la sartén, así que es de los más pesados. Si lo comes, que sea con un buen bistec o huevo y una ensalada al lado, y la porción normal, no la grande.' },
  { slug: 'rocoto-relleno', alimento: 'Rocoto relleno', nombre: 'Rocoto relleno', grupo: 'segundos',
    consejo: 'El rocoto lleva carne y queso, y casi siempre viene con pastel de papa. Un rocoto con su acompañamiento ya es un almuerzo; no hace falta sumarle arroz.' },
  { slug: 'chicharron-de-chancho', alimento: 'Chicharrón de chancho', nombre: 'Chicharrón de chancho', grupo: 'segundos',
    consejo: 'Tiene mucha proteína, pero también bastante grasa. Para un domingo está bien: una porción, con su sarsa criolla y camote, y el resto del día comes más ligero.' },
  { slug: 'carapulcra', el: 'la', alimento: 'Carapulcra', nombre: 'Carapulcra', grupo: 'segundos',
    consejo: 'La papa seca ya es tu carbohidrato. Si la acompañas con sopa seca, sírvete poquito de cada una para no duplicar.' },
  { slug: 'olluquito-con-charqui', alimento: 'Olluquito con charqui', nombre: 'Olluquito con charqui', grupo: 'segundos',
    consejo: 'Es de los platos criollos más livianos y el charqui te da proteína. Aquí casi todo lo suma el arroz: mídelo y listo.' },
  { slug: 'adobo-de-cerdo', alimento: 'Adobo de cerdo', nombre: 'Adobo de cerdo', grupo: 'segundos',
    consejo: 'Buena proteína. Elige las partes con menos grasa y acompáñalo con su camote o su pan, no con los dos.' },
  { slug: 'arroz-con-pato', alimento: 'Arroz con pato', nombre: 'Arroz con pato', grupo: 'segundos',
    consejo: 'El pato tiene más grasa que el pollo y el arroz va bien cargado. Pide la presa con menos piel y un poco menos de arroz, y le sumas su sarsa.' },
  { slug: 'frejolada', el: 'los', alimento: 'Frejolada (frejol con arroz)', nombre: 'Frejoles con arroz', grupo: 'segundos',
    consejo: 'Los frejoles llenan y tienen fibra. Si le sumas un huevo o un pedazo de pollo, tienes un plato completo y barato.' },
  { slug: 'lentejas-con-arroz', el: 'las', alimento: 'Menestra de lentejas con arroz', nombre: 'Lentejas con arroz', grupo: 'segundos',
    consejo: 'Uno de mis favoritos para el día a día: barato, llena y tiene fibra. Súmale una proteína, como pescado o huevo, y tu almuerzo está completo.' },
  { slug: 'chanfainita', el: 'la', alimento: 'Chanfainita', nombre: 'Chanfainita', grupo: 'segundos',
    consejo: 'Tiene buena proteína por el bofe y no es de los más pesados. Ojo con el arroz y el mote que la acompañan, ahí se van las calorías.' },
  { slug: 'pachamanca', el: 'la', alimento: 'Pachamanca', nombre: 'Pachamanca', grupo: 'segundos',
    consejo: 'Viene con varias carnes, papa, camote, haba y humita. Elige 2 carnes y 2 acompañamientos, no todo, y la disfrutas igual.' },
  { slug: 'estofado-de-pollo', alimento: 'Estofado de pollo', nombre: 'Estofado de pollo', grupo: 'segundos',
    consejo: 'Es un plato casero bien balanceado: pollo, papa y verduras. Con poquito arroz, o sin arroz porque ya tiene papa, queda perfecto.' },
  { slug: 'escabeche-de-pollo', alimento: 'Escabeche de pollo', nombre: 'Escabeche de pollo', grupo: 'segundos',
    consejo: 'Buena proteína y bastante cebolla. Lo que más suma es el camote y el arroz: con uno de los dos basta.' },
  { slug: 'juane', frase: 'Un juane', alimento: 'Juane', nombre: 'Juane', grupo: 'segundos',
    consejo: 'Un juane con su arroz, pollo, huevo y aceituna ya es una comida completa. Uno con su ensalada de cocona o tu cebollita, y no necesitas más.' },
  { slug: 'pollada', etiqueta: 'Un cuarto de pollo', frase: 'Un cuarto de pollada', el: 'la', alimento: 'Pollada (pollo frito)', nombre: 'Pollada', grupo: 'segundos',
    consejo: 'Es pollo frito, así que suma más que uno al horno. Si vas a una pollada, disfrútala, y el resto del día comes ligero. Una comida no te arruina el avance.' },

  // Arroces y tallarines
  { slug: 'arroz-con-pollo', alimento: 'Arroz con pollo', nombre: 'Arroz con pollo', grupo: 'arroces',
    consejo: 'Pide la presa más grande y menos arroz: más proteína y menos carbohidrato. Con su papa a la huancaína al lado ya es mucho: elige uno de los dos.' },
  { slug: 'arroz-chaufa', alimento: 'Arroz chaufa', nombre: 'Arroz chaufa', grupo: 'arroces',
    consejo: 'El chaufa es casi todo arroz con aceite. Si te provoca, pide media porción y súmale pollo o huevo, o comparte el plato.' },
  { slug: 'tallarines-verdes', el: 'los', alimento: 'Tallarines verdes', nombre: 'Tallarines verdes', grupo: 'arroces',
    consejo: 'El pesto lleva queso y aceite, y el fideo suma rápido. Media porción de tallarín con un buen bistec o pollo es un plato mucho más equilibrado.' },
  { slug: 'tallarines-rojos-con-pollo', el: 'los', alimento: 'Tallarines rojos con pollo', nombre: 'Tallarines rojos con pollo', grupo: 'arroces',
    consejo: 'La salsa roja es más liviana que la verde. Pide la presa grande y menos fideo, y tienes un almuerzo rico y completo.' },
  { slug: 'arroz-con-mariscos', alimento: 'Arroz con mariscos', nombre: 'Arroz con mariscos', grupo: 'arroces',
    consejo: 'Los mariscos tienen buena proteína, pero el plato es sobre todo arroz. Media porción con su sarsa y un ceviche de entrada es una gran combinación.' },

  // Pescados y mariscos
  { slug: 'ceviche', alimento: 'Ceviche de pescado', nombre: 'Ceviche de pescado', grupo: 'mar',
    aclara: 'Solo el ceviche: sin camote, choclo ni cancha.',
    consejo: 'El pescado con limón es de lo más sano que hay: mucha proteína y casi nada de grasa. Lo que suma es lo de al lado: camote, choclo y la cancha. Elige uno y disfruta.' },
  { slug: 'sudado-de-pescado', alimento: 'Sudado de pescado', nombre: 'Sudado de pescado', grupo: 'mar',
    consejo: 'De los mejores platos si quieres bajar: mucha proteína y poca grasa. Acompáñalo con yuca o arroz, una porción normal.' },
  { slug: 'pescado-frito', alimento: 'Pescado frito', nombre: 'Pescado frito', grupo: 'mar',
    consejo: 'El pescado es buenísimo, pero frito absorbe aceite. Si puedes, pídelo a la plancha; si es frito, acompáñalo con ensalada en vez de papas fritas.' },
  { slug: 'chupe-de-camarones', alimento: 'Chupe de camarones', nombre: 'Chupe de camarones', grupo: 'mar',
    consejo: 'Lleva leche, huevo, queso y papa, así que llena bastante. Un plato de chupe ya es tu almuerzo completo: no le sumes un segundo.' },
  { slug: 'parihuela', el: 'la', alimento: 'Parihuela', nombre: 'Parihuela', grupo: 'mar',
    consejo: 'Es de las sopas más livianas y con mucha proteína del mar. Si te quedas con hambre, súmale un poco de arroz o yuca, no pan.' },

  // Entradas
  { slug: 'causa-limena', el: 'la', alimento: 'Causa limeña', nombre: 'Causa limeña', grupo: 'entradas',
    porcion: 'media porción', etiqueta: 'Una porción de entrada',
    consejo: 'La papa amarilla y la mayonesa son las que suman. Como entrada, una porción normal está perfecta; si va de plato principal, que sea con atún o pollo.' },
  { slug: 'papa-a-la-huancaina', el: 'la', alimento: 'Papa a la huancaína', nombre: 'Papa a la huancaína', grupo: 'entradas',
    porcion: 'media porción', etiqueta: 'Una porción de entrada',
    consejo: 'La crema lleva queso, galleta y aceite. Pide la crema aparte y úsala con medida: el sabor está igual y comes bastante menos.' },
  { slug: 'ocopa', el: 'la', alimento: 'Ocopa arequipeña', nombre: 'Ocopa', grupo: 'entradas',
    porcion: 'media porción', etiqueta: 'Una porción de entrada',
    consejo: 'Es parecida a la huancaína: la salsa lleva maní, queso y galleta. Rica de entrada, pero con media porción ya está; después un segundo ligero.' },
  { slug: 'papa-rellena', frase: 'Una papa rellena', el: 'la', alimento: 'Papa rellena', nombre: 'Papa rellena', grupo: 'entradas',
    consejo: 'Una papa rellena es casi un almuerzo chico. Si la comes al paso, que sea una y con su sarsa; en vez de dos, súmale una ensalada.' },
  { slug: 'tamal', frase: 'Un tamal', alimento: 'Tamal', nombre: 'Tamal', grupo: 'entradas',
    consejo: 'Para el desayuno del domingo está bien: un tamal con su sarsa y un café. Lo que suma es acompañarlo con pan: elige uno de los dos.' },
  { slug: 'humita', frase: 'Una humita', el: 'la', alimento: 'Humita', nombre: 'Humita', grupo: 'entradas',
    consejo: 'Es choclo con manteca, rica y llenadora. Una humita es tu carbohidrato de esa comida; acompáñala con un huevo o queso fresco.' },
  { slug: 'anticuchos', porcion: 'porción (2 palitos)', etiqueta: 'Una porción de 2 palitos', frase: 'Una porción de 2 palitos de anticucho', el: 'los', alimento: 'Anticucho de corazón', nombre: 'Anticuchos de corazón', grupo: 'entradas',
    consejo: 'El corazón tiene mucha proteína y poca grasa. Lo que más suma es la papa y el choclo que vienen al lado: dos palitos con su choclo es una gran opción.' },

  // Sopas y caldos
  { slug: 'aguadito-de-pollo', alimento: 'Aguadito de pollo', nombre: 'Aguadito de pollo', grupo: 'sopas',
    consejo: 'Liviano y reconfortante. Si quieres que te llene más, pide la presa grande: así le sumas proteína sin sumar mucho más.' },
  { slug: 'caldo-de-gallina', alimento: 'Caldo de gallina', nombre: 'Caldo de gallina', grupo: 'sopas',
    consejo: 'El caldo en sí es liviano; lo que suma es el fideo, la papa y la grasa de la gallina. Pide la presa sin pellejo y un poco menos de fideo.' },
  { slug: 'sopa-a-la-minuta', el: 'la', alimento: 'Sopa a la minuta', nombre: 'Sopa a la minuta', grupo: 'sopas',
    consejo: 'Lleva carne molida, fideo y leche, y llena rápido. De entrada, media porción; o un plato entero y un segundo más ligero.' },
  { slug: 'menestron', alimento: 'Menestrón', nombre: 'Menestrón', grupo: 'sopas',
    consejo: 'Tiene muchas verduras y frejol, buen plato para llenarte con pocas calorías. Si va con carne, mejor: le sumas proteína.' },

  // Al paso
  { slug: 'pan-con-chicharron', frase: 'Un pan con chicharrón', alimento: 'Pan con chicharrón', nombre: 'Pan con chicharrón', grupo: 'paso',
    consejo: 'Es un clásico del domingo y no tienes por qué dejarlo. Uno, con su camote y su sarsa, y el resto del día comes más ligero. Comida a comida.' },
  { slug: 'salchipapa', el: 'la', alimento: 'Salchipapa', nombre: 'Salchipapa', grupo: 'paso',
    consejo: 'Papas fritas, salchicha y cremas: es de lo que más suma. Si te provoca, comparte la porción o pide la chica, y ojo con las cremas.' },
  { slug: 'butifarra', frase: 'Una butifarra', el: 'la', alimento: 'Butifarra', nombre: 'Butifarra', grupo: 'paso',
    consejo: 'Un pan con jamón del país y sarsa: ni tan pesado ni tan ligero. Uno está bien para un desayuno o lonche; dos ya es mucho.' },

  // Postres
  { slug: 'picarones', el: 'los', alimento: 'Picarones con miel', nombre: 'Picarones con miel', grupo: 'postres',
    consejo: 'Son fritos y con miel, así que suman bastante. Comparte la porción o pide menos miel, y disfrútalos de vez en cuando, sin culpa.' },
  { slug: 'mazamorra-morada', el: 'la', alimento: 'Mazamorra morada', nombre: 'Mazamorra morada', grupo: 'postres',
    consejo: 'Es de los postres más livianos porque casi no tiene grasa. Una porción normal después del almuerzo está bien.' },
  { slug: 'arroz-con-leche', alimento: 'Arroz con leche', nombre: 'Arroz con leche', grupo: 'postres',
    consejo: 'No es de los más pesados, pero tiene bastante azúcar. Una porción chica, o un combinado a medias con mazamorra, y listo.' },
  { slug: 'suspiro-a-la-limena', alimento: 'Suspiro a la limeña', nombre: 'Suspiro a la limeña', grupo: 'postres',
    consejo: 'Manjar y merengue: es muy dulce y suma rápido. Una copa chica para compartir es la mejor forma de disfrutarlo.' },
  { slug: 'turron-de-dona-pepa', alimento: 'Turrón de Doña Pepa', nombre: 'Turrón de Doña Pepa', grupo: 'postres',
    consejo: 'Cuando llega octubre se antoja, y está bien darse el gusto. Una tajada delgada, no la porción grande, y la cuentas en tu día.' },
  { slug: 'torta-tres-leches', el: 'la', alimento: 'Torta tres leches', nombre: 'Torta tres leches', grupo: 'postres',
    consejo: 'Una tajada normal no es tan terrible como parece. Lo importante es que sea una y que la cuentes en tu día.' },

  // Segundo grupo (30 platos más)
  { slug: 'arroz-con-chancho', alimento: 'Arroz con chancho', nombre: 'Arroz con chancho', grupo: 'arroces',
    consejo: 'El chancho tiene más grasa que el pollo y el arroz va bien cargado. Pide menos arroz, más carne magra y su sarsa al lado.' },
  { slug: 'arroz-chaufa-especial', alimento: 'Arroz chaufa especial', nombre: 'Arroz chaufa especial', grupo: 'arroces',
    consejo: 'El especial trae más carnes que el simple, y eso suma proteína. Igual es bastante arroz: media porción o compartido es la jugada.' },
  { slug: 'arroz-a-la-jardinera', alimento: 'Arroz a la jardinera', nombre: 'Arroz a la jardinera', grupo: 'arroces',
    consejo: 'Las verduras ayudan, pero sigue siendo arroz con aceite. Úsalo como acompañamiento, media porción, al lado de una buena proteína.' },
  { slug: 'tallarines-rojos-con-carne', el: 'los', alimento: 'Tallarines rojos con carne molida', nombre: 'Tallarines rojos con carne molida', grupo: 'arroces',
    consejo: 'La salsa con carne molida da proteína y sabor. Sírvete más salsa y menos fideo, y súmale una ensalada.' },
  { slug: 'chicharron-de-pollo', alimento: 'Chicharrón de pollo', nombre: 'Chicharrón de pollo', grupo: 'segundos',
    consejo: 'Es pollo, pero frito y empanizado, así que suma más que uno a la plancha. Una porción con ensalada y yuca, sin papas fritas, y lo disfrutas igual.' },
  { slug: 'pollo-al-horno', alimento: 'Pollo al horno', nombre: 'Pollo al horno', grupo: 'segundos',
    etiqueta: 'Una presa', frase: 'Una presa de pollo al horno',
    consejo: 'De mis favoritos para el día a día: mucha proteína y poca preparación. Quítale la piel si quieres que sea aún más ligero y acompáñalo con lo que quieras.' },
  { slug: 'pollo-al-sillao', alimento: 'Pollo al sillao', nombre: 'Pollo al sillao', grupo: 'segundos',
    consejo: 'El sillao le da sabor sin muchas calorías; lo que suma es el aceite y el arroz. Media porción de arroz y le sumas verduras salteadas.' },
  { slug: 'pollo-a-la-olla', alimento: 'Pollo a la olla con arroz', nombre: 'Pollo a la olla con arroz', grupo: 'segundos',
    consejo: 'Es un plato casero bien completo: pollo, papa, verduras y arroz. Como ya trae papa, con poquito arroz ya está.' },
  { slug: 'estofado-de-carne', alimento: 'Estofado de carne', nombre: 'Estofado de carne', grupo: 'segundos',
    consejo: 'Buena proteína y viene con papa y verduras. Mide el arroz y tienes un almuerzo completo y rico.' },
  { slug: 'pollo-broaster', alimento: 'Pollo broaster', nombre: 'Pollo broaster', grupo: 'segundos',
    frase: 'Una presa de pollo broaster',
    consejo: 'El empanizado y la fritura son los que suman. Si te provoca, una presa con ensalada en vez de papas, y ojo con las cremas.' },
  { slug: 'pollo-a-la-brasa-sin-papas', alimento: 'Pollo a la brasa (solo la presa)', nombre: 'Pollo a la brasa sin papas', grupo: 'segundos',
    etiqueta: 'Un cuarto de pollo', frase: 'Un cuarto de pollo a la brasa, solo la presa',
    consejo: 'Sin papas fritas el pollo a la brasa cambia muchísimo: es pura proteína. Pídelo con ensalada y unas pocas papas o camote, y ya tienes un plato muy bueno.' },
  { slug: 'milanesa-de-pollo', el: 'la', alimento: 'Milanesa de pollo', nombre: 'Milanesa de pollo', grupo: 'segundos',
    etiqueta: 'Un filete', frase: 'Un filete de milanesa de pollo',
    consejo: 'El pollo es buenísimo, el empanizado frito es el que suma. Si la haces en casa, al horno o en freidora de aire queda rica y más ligera.' },
  { slug: 'alitas-acevichadas', el: 'las', alimento: 'Alitas acevichadas (carrito)', nombre: 'Alitas acevichadas', grupo: 'paso',
    porcion: 'porción (6 unidades)', etiqueta: 'Una porción de 6 alitas', frase: 'Una porción de 6 alitas acevichadas',
    consejo: 'Seis alitas con su salsa ya son casi mil calorías, y eso sin papas. Pide 4, compártelas, y cambia las papas por ensalada.' },
  { slug: 'salchipollo', alimento: 'Salchipollo', nombre: 'Salchipollo', grupo: 'paso',
    consejo: 'Pollo frito, salchicha y papas fritas: de lo que más suma. Si te provoca, que sea compartido y de vez en cuando, sin culpa.' },
  { slug: 'pan-con-pollo', alimento: 'Pan con pollo', nombre: 'Pan con pollo', grupo: 'paso',
    frase: 'Un pan con pollo',
    consejo: 'Uno de los panes más balanceados: pollo deshilachado y pan. Ojo con la mayonesa, que es la que más suma; con lechuga y tomate queda igual de rico.' },
  { slug: 'pan-con-jamonada', alimento: 'Pan con jamonada', nombre: 'Pan con jamonada', grupo: 'paso',
    frase: 'Un pan con jamonada',
    consejo: 'Un pan con jamonada no es tan pesado, pero tiene poca proteína. Si lo cambias por pan con huevo o queso fresco, te llena más.' },
  { slug: 'hamburguesa-de-carretilla', el: 'la', alimento: 'Hamburguesa de carretilla', nombre: 'Hamburguesa de carretilla', grupo: 'paso',
    frase: 'Una hamburguesa de carretilla',
    consejo: 'La carne y el pan no son el problema: son las papitas al hilo y las cremas. Pídela con lechuga y tomate, y menos cremas.' },
  { slug: 'empanada-de-carne', el: 'la', alimento: 'Empanada de carne', nombre: 'Empanada de carne', grupo: 'paso',
    frase: 'Una empanada de carne',
    consejo: 'Una empanada es un buen lonche, pero la masa suma. Una con un café o un refresco sin azúcar está bien; dos ya es una comida.' },
  { slug: 'empanada-de-pollo', el: 'la', alimento: 'Empanada de pollo', nombre: 'Empanada de pollo', grupo: 'paso',
    frase: 'Una empanada de pollo',
    consejo: 'Un poquito más ligera que la de carne. Una para el lonche y la acompañas con una fruta en vez de una gaseosa.' },
  { slug: 'sopa-wantan', el: 'la', alimento: 'Sopa wantán', nombre: 'Sopa wantán', grupo: 'sopas',
    consejo: 'Es de las entradas más livianas del chifa. Pídela antes del plato de fondo y te ayuda a comer menos arroz chaufa después.' },
  { slug: 'sopa-de-pollo', el: 'la', alimento: 'Sopa de pollo con fideos', nombre: 'Sopa de pollo con fideos', grupo: 'sopas',
    consejo: 'Liviana y reconfortante. Pide la presa grande y menos fideo, y es una cena perfecta.' },
  { slug: 'locro-de-zapallo', alimento: 'Locro de zapallo', nombre: 'Locro de zapallo', grupo: 'segundos',
    consejo: 'Zapallo, papa, choclo y queso: llena bastante y no es pesado. Si lo acompañas con arroz, que sea poquito, y súmale un huevo para la proteína.' },
  { slug: 'ensalada-rusa', el: 'la', alimento: 'Ensalada rusa', nombre: 'Ensalada rusa', grupo: 'entradas',
    consejo: 'Tiene papa, zanahoria y beterraga, pero lo que suma es la mayonesa. Prepárala con menos mayonesa o con yogur natural y queda rica igual.' },
  { slug: 'combinado', alimento: 'Combinado (mazamorra + arroz con leche)', nombre: 'Combinado (mazamorra con arroz con leche)', grupo: 'postres',
    consejo: 'El clásico de la esquina. Uno chico de vez en cuando está bien; compártelo si es el grande.' },
  { slug: 'alfajor', alimento: 'Alfajor', nombre: 'Alfajor', grupo: 'postres',
    frase: 'Un alfajor',
    consejo: 'Chiquito pero con mucho manjar y mantequilla. Uno con tu café está bien, sin culpa; el tema es cuando se van tres.' },
  { slug: 'paneton', alimento: 'Panetón', nombre: 'Panetón', grupo: 'navidad',
    etiqueta: 'Una tajada', frase: 'Una tajada de panetón',
    consejo: 'En diciembre no tienes por qué dejarlo. Una tajada con tu chocolate, y la cuentas en tu día. Comida a comida.' },
  { slug: 'leche-asada', el: 'la', alimento: 'Leche asada', nombre: 'Leche asada', grupo: 'postres',
    consejo: 'De los postres más ligeros que hay: leche y huevo, así que trae algo de proteína. Una porción después del almuerzo está bien.' },
  { slug: 'crema-volteada', el: 'la', alimento: 'Flan / crema volteada', nombre: 'Crema volteada', grupo: 'postres',
    consejo: 'Parecida a la leche asada, pero con más caramelo. Una porción normal, y listo.' },
  { slug: 'chicha-morada', el: 'la', alimento: 'Chicha morada con azúcar', nombre: 'Chicha morada', grupo: 'bebidas',
    porcion: 'vaso', etiqueta: 'Un vaso', frase: 'Un vaso de chicha morada', aclara: 'Con azúcar, como se sirve normalmente.',
    consejo: 'El maíz morado es buenísimo; lo que suma es el azúcar. Prepárala con la mitad del azúcar o con endulzante y la puedes tomar más seguido.' },
  { slug: 'emoliente', alimento: 'Emoliente', estado: 'Con azúcar', nombre: 'Emoliente', grupo: 'bebidas',
    porcion: 'vaso', etiqueta: 'Un vaso', frase: 'Un vaso de emoliente', aclara: 'Con azúcar, como se vende en la carretilla.',
    consejo: 'Las hierbas casi no tienen calorías; lo que suma es el azúcar. Pídelo con poquita azúcar y es de las mejores bebidas calientes.' },

  // Navidad
  { slug: 'chocolatada-navidena', el: 'la', alimento: 'Chocolatada navideña', nombre: 'Chocolatada navideña', grupo: 'navidad',
    etiqueta: 'Una taza', frase: 'Una taza de chocolatada navideña', aclara: 'Hecha en casa con leche evaporada, chocolate de taza y azúcar.',
    consejo: 'Es de las cosas más ricas de diciembre y no tienes por qué dejarla. Una taza con tu tajada de panetón y la cuentas en tu día. Si la preparas tú, con menos azúcar queda igual de rica.' },
  { slug: 'pavo-al-horno', alimento: 'Pavo al horno (con piel)', nombre: 'Pavo al horno', grupo: 'navidad',
    etiqueta: 'Una porción', frase: 'Una porción de pavo al horno',
    consejo: 'El pavo es de lo mejor de la cena: mucha proteína. Lo que suma son los acompañamientos. Sírvete una buena porción de pavo y ve más tranquilo con el puré, el arroz y la ensalada rusa.' },
  { slug: 'lechon-al-horno', alimento: 'Lechón al horno', nombre: 'Lechón al horno', grupo: 'navidad',
    etiqueta: 'Una porción', frase: 'Una porción de lechón al horno',
    consejo: 'El lechón tiene más grasa que el pavo, sobre todo la piel crocante. Si hay de los dos, combina: un poco de cada uno y una porción normal. Es una noche para disfrutar, sin culpa.' },
  { slug: 'pure-de-manzana', alimento: 'Puré de manzana', nombre: 'Puré de manzana', grupo: 'navidad',
    consejo: 'Es ligero: casi todo es la fruta con su azúcar. Un par de cucharadas al lado de tu pavo está perfecto.' },
];
